mode:
  type: mono
  wavelength: 760.  # nm
surface:
  type: lambertian
  reflectance: 0.5  # dimensionless
atmosphere:
  type: rayleigh_homogeneous
  height: 40.  # km
illumination:
  type: directional
  zenith: 30.  # deg
  azimuth: 0.  # deg
  irradiance: 1.8e+6  # W/km^2/nm
measure:
  type: hemispherical
  spp: 32000  # dimensionless
  zenith_res: 10.  # deg
  azimuth_res: 10.  # deg
