mode:
  type: mono
  wavelength: 760.  # nm
surface:
  type: lambertian
  reflectance: 0.35  # dimensionless
atmosphere:
  type: rayleigh_homogeneous
  height: 100  # km
  sigma_s_params:
    refractive_index: 1.0003  # dimensionless
illumination:
  type: directional
  zenith: 0.  # deg
  azimuth: 0.  # deg
  irradiance: 1800000.  # W/km^2/nm
measure:
  type: distant
  zenith: [0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]  # deg
  azimuth: [0., 90., 180., 270.]  # deg